merkledag.go
merkledag_test.go

This adds also EnumerateChildren*Depth which call a visit function which
receives the Cid and the depth in the dag at which it has been seen.

Add FetchGraphWithDepthLimit to specify depth-limited graph fetching.

---

coding.go
node_test.go
package.json
pb/merkledag.pb.go
pb/upgrade_check.go

This will allow us to address https://github.com/libp2p/go-libp2p-kad-dht/issues/177 without forcing us to change the go APIs too much.
We've wanted to do this for a while anyways.

update gogo protobuf

---

node_test.go
package.json

removes all `// import` directives from the protobuf source

fix the protobuf import

---

coding.go
node.go
raw.go

Depends on https://github.com/ipfs/go-cid/pull/53.

Update to use new Builder interface for creating CIDs.

---

node.go

After @whyrusleeping demonstrated us how to find slow code, I went and made this a bit faster.
Test used to profile is in `go-mfs`
pprof before
pprof after

perf: avoid allocations when filtering nodes

---

.gx/lastpubver
coding.go
errservice.go
merkledag.go
merkledag_test.go
node.go
package.json
readonly_test.go
rwservice.go

See https://github.com/ipfs/go-cid/pull/71 for additional info.
Depends on:
Which Depends on:
- https://github.com/ipfs/go-bitswap/pull/10
- https://github.com/ipfs/go-block-format/pull/14
- https://github.com/ipfs/go-cid/pull/71
- https://github.com/ipfs/go-ipfs-blockstore/pull/15
- https://github.com/ipfs/go-ipfs-blocksutil/pull/2
- https://github.com/ipfs/go-ipfs-ds-help/pull/6
- https://github.com/ipfs/go-ipfs-exchange-interface/pull/2
- https://github.com/ipfs/go-ipfs-exchange-offline/pull/8
- https://github.com/ipfs/go-ipfs-routing/pull/13
- https://github.com/ipfs/go-ipld-cbor/pull/40
- https://github.com/ipfs/go-ipld-format/pull/42
- https://github.com/libp2p/go-libp2p-routing/pull/27
- https://github.com/ipfs/go-verifcid/pull/3
Please approve but do not merge. Depends on locally …

gx update and fix code to use new Cid type

---

merkledag.go

Make sure than when EnumerateChildrenAsync returns, all of it's go routines have completed, even in the case of a context cancel
Add a waitGroup that waits for all of the graph traversal child go routines to terminate before the function terminates
Reasoning:
See https://github.com/ipfs/go-unixfs/pull/39#discussion_r229400182
In the case of a context cancel, the select loop in the main thread of `EnumerateChildrenAsyncDepth` can receive the cancel before it's processed by the go routines enumerating children. This can cause the `EnumerateChildrenAsyncDepth` to return with these enumeration routines still in progress, and therefore for getLinks() to get called up to one time per channel after the overall routine returns.
The consequences for the caller of the function can be super …

Wait for all go routines to finish before function returns

---

merkledag.go

Given all the bitswap session improvements, I think it's time to give our users some candy. This should allow us to actually take advantage of the increased wantlist sizes.

Increase FetchGraphConcurrency to 32

---

coding.go
node.go

This is also a bugfix as we don't want to re-encode nodes unless we change them. If we do and the user chose a non-standard encoding, we could change the CID. This is likely what triggered https://github.com/ipfs/go-ipfs/issues/6011

fix some performance regressions when reading protobuf nodes

---

merkledag_test.go
raw.go

fixes https://github.com/ipfs/go-ipfs/issues/6076

add function to marshal raw nodes to json

---

merkledag.go
merkledag_test.go

This fixes the inconsistent EnumerateChildrenAsync behavior by renaming everything.
1. EnumerateChildrenAsync has been renamed to WalkParallel because it visited root in addition to the children and isn't async (it's _parallel_).
2. EnumerateChildren has been renamed to Walk and now _also_ visits the root for consistency.
Anyone needing to skip the root can do so manually (`if c.Equals(root)` ...).
This is an _intentionally_ breaking change to force an audit of all callsites.
Q: Should we leave an (additional) EnumerateChildren function? That function does _exactly_ what it says already.

fix inconsistent EnumerateChildrenAsync behavior

---

merkledag.go
merkledag_test.go

This PR:
- reduce the walk API to 2 simpler functions
- add consistent and clear control over if the root should be visited
- add control over the concurrency factor
I also want to implement a `IgnoreBadBlock()` options to continue walking even when a bad block is read.
Note: `FetchGraphWithDepthLimit` could be made simpler with a `DepthLimit()` option as well.
@Stebalien

rework the graph walking functions with functional options

---

merkledag.go
merkledag_test.go

1. Walk implies walking the entire graph.
2. Avoids a _silent_ breaking change.

fix: include root in searches by default

---

node.go
node_test.go

ipld.ErrNotFound should only be used when the underlying node isn't found

fix: return ErrLinkNotFound when the _link_ isn't found

---

merkledag.go

fix: slightly reduce memory usage when walking large directory trees

---

coding.go

Solves https://github.com/ipfs/go-merkledag/issues/48 and enables a public `GetPBNode` function. I left out specific tests, since this function is covered by other tests.

Make getPBNode Public

---

merkledag.go

This way, the caller can pass in any dag service that implements the
SessionMaker interface.

fix: correctly construct sessions

---

pb/compat_test.go

Trying to pin down a precise schema for DAG-PB.
Ref: https://github.com/ipld/specs/pull/297
Relevant findings:
1. Most things can be `nil`.
2. `Links:[]` is not possible, zero-length `Links` becomes `nil`, this isn't the case for `Name` or `Hash` when they are zero length. This also means `{ Data: nil, Links: [] } === { Data: nil, Links: nil } === {}`.
3. Unmarshalling zero bytes is a valid operation and yields ^ that (`{ Data: nil, Links: nil }`). I'm not really sure what to do with that information but it's worth noting. I'm sure others already know this but perhaps this should go into the DAG-PB spec if it's allowable by other components of the IPLD stack. So there would be a canonical CID for an empty PB block for any given multihash. That would be …

chore: add tests to verify allowable data layouts

---

dagutils/diff.go
dagutils/diff_test.go

This fixes a bug where conflicts were also returned as changes when merged.

Fix bug in dagutils MergeDiffs.

---

raw.go

As far as I understand there is no reason not to return proper values here.

fix RawNode incomplete stats

---

coding.go
merkledag_test.go
node.go

When decoding a badly serialised block with Links out of order, don't sort
the list until we receive an explicit mutation operation. This ensures stable
DAG traversal ordering based on the links as they appear in the serialised
form and removes surprise-sorting when performing certain operations that
wouldn't be expected to mutate.
The pre-v0.4.0 behaviour was to always sort, but this behaviour wasn't baked
in to the dag-pb spec and wasn't built into go-codec-dagpb which now forms the
backend of ProtoNode, although remnants of sorting remain in some operations.
Almost all CAR-from-DAG creation code in Go uses go-codec-dagpb and
go-ipld-prime's traversal engine. However this can result in a different order
when encountering badly encoded blocks (unsorted Links) where certain
intermediate …

fix!: keep ProtoNode deserialised state stable until explicit mutation

---

go.mod
go.sum
merkledag_test.go
node.go

Ref: https://github.com/ipfs/go-merkledag/issues/90
When using `SetCidBuilder` you can set up for a hasher that will not be found when a `Sum()` is eventually called in `EncodeProtobuf()`, and the error from this doesn't bubble up through `RawData()`, it just panics.
So this change adds an error return to `SetCidBuilder()` _and_ will fail to use the builder if it's going to result in that error. If the error isn't handled then you'll get a silent default to a (presumably) working builder. If it's checked then at least you'll have an error to bubble up to the user or some place helpful.
However, the caveat here is that we are not actually testing `Sum()` will work, only the obvious path to the error. If we are given a custom `CidBuilder` that doesn't match `Prefix`, or if there is a custom …

feat: check that the CidBuilder hasher is usable

---

coding.go
merkledag_test.go
node.go
version.json

Attempt to keep ProtoNode always in a state that can be encoded without errors to avoid cases where the panicing methods may be forced to panic on error.
go-codec-dagpb will error when encoding either of the following cases:
* The Hash field in links should always be set, cannot be cid.Undef
* The Tsize field needs to fit into an int64, otherwise it'll overflow to negative which is not allowed
Error on cases where a user may attempt to set links that will eventually error on encode. Then when we do encode, silently handle these cases if they manage to slip through (e.g. if they come in from a decoded block with a bad form).

feat: check links on setting and sanitise on encoding

---

CODEOWNERS
README.md

Making clear the repo status per https://github.com/ipfs/boxo/issues/218
Note that no "deprecated types" are being added.  There is only a general notice that this repo is on a deprecation path and a pointer to the code copy that Kubo uses.  Any code that @ipfs/kubo-maintainers own will switch to the Boxo version.  A CODEOWNERS was added to clarify who will look at any PRs or do mandatory fixes here (likely in sync with @ipfs/kubo-maintainers since both sides are generally only doing critical changes here.)

Update README.md and added CODEOWNERS
